### PR TITLE
Remove Mark from Cryptography (EF)

### PR DESCRIPTION
**Pull request by mmaller**
Mark has moved on from Cryptography (EF)

### CODE REVIEW

**Review by hwwhww — APPROVED** [review]

**Comment by dankrad** [comment]
I think Mark is strongly committed to continue working on Ethereum research. So given that the idea of PG is to have a source of funding that is not dependent on a given organization, I think he should remain a PG member unless he actually ceases work on Ethereum-related research.

**Comment by cheeky-gorilla** [comment]
We'll need confirmation from Mark (@msimkin) - will you continue contributing to eligible work? 

If you're not 100% sure, or not 100% clear on the timeline, then probably it would be best to leave the membership for now. We can always consider adding you back in the future (your weight aka Split share wouldn't reset, it would resume where it was, whatever time off in between would count as "time off").

**Comment by msimkin** [comment]
Hey, 

I am currently actively working on research projects directly contributing to Ethereum and I plan to continue doing so for the time being.
Does that answer the question?

Cheers,  
   Mark

**Comment by cheeky-gorilla** [comment]
Thanks Mark! Two more questions for ya:

1. Will you still be contributing to eligible work in a full-time capacity? 
2. Will you still be collaborating with the EF's Cryptography team on this, or some other team(s)?

**Comment by msimkin** [comment]
Hey, 

Yes I am planning to do this full time and I am currently and plan to continue actively collaborating (we have multiple research papers we are writing right now) with researchers from the EF cryptography team and other EF research teams as well.

Cheers, 
   Mark

**Comment by cheeky-gorilla** [comment]
Given Mark's confirmation above that we will continue contributing to eligible work, and having chatted with a few ppl including Mary, we agreed to close this PR, Mark remains a PG member 🥂

Instead, @msimkin please create a new PR to remove your "Team" affiliation and add your "Primary Contributions", here's two examples: 

1. https://github.com/protocolguild/documentation/pull/185
2. https://github.com/protocolguild/documentation/pull/200

Thanks everyone!

**Comment by cheeky-gorilla** [comment]
Hey @msimkin - could you provide us with an update on your membership eligibility? We currently have you as working full-time on [eligible projects](https://protocol-guild.readthedocs.io/en/latest/01-eligibility.html), has anything changed there?

**Comment by msimkin** [comment]
Nothing changed, still valid. Working on research projects surrounding data availability sampling for Ethereum.

**Comment by cheeky-gorilla** [comment]
Thanks! And for verification, could you share which PG members could vouch for this work (or ask them to reach out me)?

**Pull request closed without merging**
