### PR TITLE
Add Paul Hauner

### PR DESCRIPTION
**Pull request by AgeManning**
# Name

Paul Hauner

# Team

Lighthouse

# Link to Some Work

https://github.com/sigp/lighthouse/pulls?q=author%3Apaulhauner

# Eligibility

Paul has been working on Lighthouse since its inception. He was removed from the Protocol Guild a few months ago as he had taken extended leave. He has since returned and this PR is to add him back to the Protocol Guild at half-weight. 

# Proposed Weight

Half (0.5) - Paul has multiple responsibilities. Although Lighthouse and Ethereum specs are his major priority, he technically cannot be classed as full-time on these projects.

### CODE REVIEW

**Comment by AgeManning** [comment]
cc @paulhauner

**Comment by paulhauner** [comment]
Indeed, I am back! Thanks for authoring this @AgeManning 🙏

**Review by ralexstokes — APPROVED** [review]
welcome back :)

**Review by mkalinin — APPROVED** [review]
Welcome back!!

**Review by rolfyone — APPROVED** [review]

**Review by terencechain — APPROVED** [review]

**Pull request merged**
