### PR TITLE
Add Grandine to eligible client list

### PR DESCRIPTION
**Pull request by timbeiko**
**Sep 24 update:** 
After internal PG discussions, it seems like the best start date for the project would be when the client was open-sourced. So, for clarity: 

- Name of project: Grandine
- Eligibility start date for the project: March 2024
- Summary of why this project should be considered eligible/ineligible: see below

- - -  

After an internal temp-check, I'd like to propose Grandine be added as an eligible PG project. 

The client, which recently [open-sourced](https://medium.com/@grandine/grandine-is-open-sourced-b1815cf0ae39), has been in development since 2019. It currently runs on the latest [Pectra devnet](https://forkmon.pectra-devnet-3.ethpandaops.io/) and the team is engaged in Ethereum R&D across multiple venues. 

While I don't believe this should be a deciding factor in their eligibility, it is worth noting the client relies on an external library, [eth2_libp2p](https://github.com/grandinetech/eth2_libp2p/tree/d60c9f1d77d163d319d7a46a2e8acc8e1cf8d2df), for portions of their p2p stack. 

Assuming the project is included in PG, we should decide whether contributors' closed-source contributions (2019-2024) should accrue towards their weight, or if only OSS contributions are counted (March 2024 and onwards).

### CODE REVIEW

**Review by ensi321 — APPROVED** [review]
Personally support it ❤️

**Review by tersec — APPROVED** [review]

**Review by tbenr — APPROVED** [review]

**Review by terencechain — APPROVED** [review]

**Review by SamWilsn — COMMENTED** [review]
Looks like they require a [CLA](https://cla-assistant.io/grandinetech/grandine) with a pretty broad license. How do we feel about those?

**Review by michaelsproul — APPROVED** [review]

**Review by ralexstokes — APPROVED** [review]
lgtm!

> or if only OSS contributions are counted (March 2024 and onwards).

id also lean towards this

**Review by mkalinin — APPROVED** [review]

**Comment by SamWilsn** [comment]
As a contributor, I'm a little nervous about CLAs like this one because they would allow you to take my contributions and re-release them under a closed source license in the future.

Would you consider choosing "Option 1", "Option 2" (with a reasonable list), or "Option 3" from the copyright page of the wizard? These options ensure that any contributions remain open source forever, while still preserving the freedom to change open source licenses if necessary.

**Comment by arnetheduck** [comment]
Of the PG projects I've considered to directly contribute to, both Prysm and Lighthouse have CLA:s in place so it's broadly hard to hold this against Grandine based on current membership regardless of the chilling effects it has on contributions.

**Comment by philknows** [comment]
ChainSafe also requires [signing a CLA that's very broad](https://cla-assistant.io/ChainSafe/lodestar) (it was implemented even before I started there so I don't know the context behind it - am also not a lawyer), so I wouldn't hold this against them unless we all revise/review our CLAs with our orgs if it's a larger issue at hand. But it shouldn't block the eligibility of Grandine IMO.

**Comment by sauliusgrigaitis** [comment]
@SamWilsn GPL already allows your contributions to be used in modified closed-source. So anyone can freely modify the GPL-licensed beacon node and run it without disclosing the modifications (google "gpl loophole agpl"). Instead, you should be insisting that all clients must switch to AGPL because only this license (at least legally) ensures that modifications are not used in closed-source projects.

**Comment by SamWilsn** [comment]
While it's true GPL allows you to run modified software and provide services over the network without disclosing the source, it doesn't permit distributing closed source binaries. I'm not saying that this is something you're planning on doing, but it is theoretically possible for you to provide upgraded closed source features to your paying customers. That would not be possible under GPL without a CLA.

---

As I mentioned on the PG chat, I'm not strongly objecting to Grandine joining Protocol Guild. We have several clients with similar CLAs. I'd just prefer if the CLA was a bit more open source/free software aligned.

**Comment by sauliusgrigaitis** [comment]
@SamWilsn I appreciate your comments, but overall I tend to not agree with you. Multiple other clients use permissive licenses (Apache/MIT) that allow your described scenario. So if we would have a permissive licence then for sure no one would raise a question that theoretically we can sell upgraded closed source features to paying costumers.

**Pull request merged**
