### PR TITLE
Add Anton Nashatyrev contribution links

### PR DESCRIPTION
**Pull request by Nashatyrev**

### CODE REVIEW

**Review by tvanepps — COMMENTED** [review]
repo links should be in the same format

consensys/teku
libp2p/jvm-libp2p

**Comment by tvanepps** [comment]
sorry one other thing - should the libp2p link be removed, is it PG eligible work? or am i missing something

**Comment by Nashatyrev** [comment]
@tvanepps I believe so: Libp2p is the base Consensus Layer protocol

**Comment by tvanepps** [comment]
> With respect to jvm-libp2p specifically, it was initially implemented as the minimal subset of libp2p to support Consensus Layer and Teku in particular as there were no other JVM libp2p implementations. It is still maintained by the Teku team and the vast majority of work is performed to support Teku needs. So from this perspective jvm-libp2p could be treated as a part of Teku. Similarly some other clients have their own libp2p repo clones

merging this with more context from discussion elsewhere

**Pull request merged**
