### PR TITLE
Remove djrtwo

### PR DESCRIPTION
**Pull request by hwwhww**
The saddest commit I've ever made.

https://github.com/djrtwo/writing/blob/main/docs/2024-09-13_goodbye-for-now.md

### CODE REVIEW

**Comment by terencechain** [comment]
😿

**Review by lightclient — APPROVED** [review]

**Review by CarlBeek — APPROVED** [review]

**Comment by potuz** [comment]
:sob:

**Comment by dapplion** [comment]
> ideally the individual themselves makes the PR, in lieu of that can @djrtwo just confirm?

I appreciate the optimism of that tag reaching Danny

**Review by skylenet — APPROVED** [review]

**Review by rolfyone — APPROVED** [review]

**Comment by djrtwo** [comment]
sorry I didn't do this myself!

<3 pg

**Pull request merged**
